

// A mapping of international dialing codes to flag emojis.
export const PHONE_PREFIX_TO_FLAG: Record<string, string> = {
  // North American Numbering Plan
  '+1242': '🇧🇸', '+1246': '🇧🇧', '+1264': '🇦🇮', '+1268': '🇦🇬', '+1284': '🇻🇬',
  '+1340': '🇻🇮', '+1345': '🇰🇾', '+1441': '🇧🇲', '+1473': '🇬🇩', '+1649': '🇹🇨',
  '+1664': '🇲🇸', '+1670': '🇲🇵', '+1671': '🇬🇺', '+1684': '🇦🇸', '+1721': '🇸🇽',
  '+1758': '🇱🇨', '+1767': '🇩🇲', '+1784': '🇻🇨', '+1809': '🇩🇴', '+1829': '🇩🇴',
  '+1849': '🇩🇴', '+1868': '🇹🇹', '+1869': '🇰🇳', '+1876': '🇯🇲', '+1939': '🇵🇷',
  '+1': '🇺🇸', // Default +1 to US
  '+7': '🇷🇺', // Russia / Kazakhstan
  '+20': '🇪🇬', '+27': '🇿🇦', '+30': '🇬🇷', '+31': '🇳🇱', '+32': '🇧🇪', '+33': '🇫🇷',
  '+34': '🇪🇸', '+36': '🇭🇺', '+39': '🇮🇹', '+40': '🇷🇴', '+41': '🇨🇭', '+43': '🇦🇹',
  '+44': '🇬🇧', '+45': '🇩🇰', '+46': '🇸🇪', '+47': '🇳🇴', '+48': '🇵🇱', '+49': '🇩🇪',
  '+51': '🇵🇪', '+52': '🇲🇽', '+53': '🇨🇺', '+54': '🇦🇷', '+55': '🇧🇷', '+56': '🇨🇱',
  '+57': '🇨🇴', '+58': '🇻🇪', '+60': '🇲🇾', '+61': '🇦🇺', '+62': '🇮🇩', '+63': '🇵🇭',
  '+64': '🇳🇿', '+65': '🇸🇬', '+66': '🇹🇭', '+81': '🇯🇵', '+82': '🇰🇷', '+84': '🇻🇳',
  '+86': '🇨🇳', '+90': '🇹🇷', '+91': '🇮🇳', '+92': '🇵🇰', '+93': '🇦🇫', '+94': '🇱🇰',
  '+95': '🇲🇲', '+98': '🇮🇷', '+211': '🇸🇸', '+212': '🇲🇦', '+213': '🇩🇿', '+216': '🇹🇳',
  '+218': '🇱🇾', '+220': '🇬🇲', '+221': '🇸🇳', '+222': '🇲🇷', '+223': '🇲🇱', '+224': '🇬🇳',
  '+225': '🇨🇮', '+226': '🇧🇫', '+227': '🇳🇪', '+228': '🇹🇬', '+229': '🇧🇯', '+230': '🇲🇺',
  '+231': '🇱🇷', '+232': '🇸🇱', '+233': '🇬🇭', '+234': '🇳🇬', '+235': '🇹🇩', '+236': '🇨🇫',
  '+237': '🇨🇲', '+238': '🇨🇻', '+239': '🇸🇹', '+240': '🇬🇶', '+241': '🇬🇦', '+242': '🇨🇬',
  '+243': '🇨🇩', '+244': '🇦🇴', '+245': '🇬🇼', '+246': '🇮🇴', '+248': '🇸🇨', '+249': '🇸🇩',
  '+250': '🇷🇼', '+251': '🇪🇹', '+252': '🇸🇴', '+253': '🇩🇯', '+254': '🇰🇪', '+255': '🇹🇿',
  '+256': '🇺🇬', '+257': '🇧🇮', '+258': '🇲🇿', '+260': '🇿🇲', '+261': '🇲🇬', '+262': '🇷🇪',
  '+263': '🇿🇼', '+264': '🇳🇦', '+265': '🇲🇼', '+266': '🇱🇸', '+267': '🇧🇼', '+268': '🇸🇿',
  '+269': '🇰🇲', '+290': '🇸🇭', '+291': '🇪🇷', '+297': '🇦🇼', '+298': '🇫🇴', '+299': '🇬🇱',
  '+350': '🇬🇮', '+351': '🇵🇹', '+352': '🇱🇺', '+353': '🇮🇪', '+354': '🇮🇸', '+355': '🇦🇱',
  '+356': '🇲🇹', '+357': '🇨🇾', '+358': '🇫🇮', '+359': '🇧🇬', '+370': '🇱🇹', '+371': '🇱🇻',
  '+372': '🇪🇪', '+373': '🇲🇩', '+374': '🇦🇲', '+375': '🇧🇾', '+376': '🇦🇩', '+377': '🇲🇨',
  '+378': '🇸🇲', '+379': '🇻🇦', '+380': '🇺🇦', '+381': '🇷🇸', '+382': '🇲🇪', '+383': '🇽🇰',
  '+385': '🇭🇷', '+386': '🇸🇮', '+387': '🇧🇦', '+389': '🇲🇰', '+420': '🇨🇿', '+421': '🇸🇰',
  '+423': '🇱🇮', '+500': '🇫🇰', '+501': '🇧🇿', '+502': '🇬🇹', '+503': '🇸🇻', '+504': '🇭🇳',
  '+505': '🇳🇮', '+506': '🇨🇷', '+507': '🇵🇦', '+508': '🇵🇲', '+509': '🇭🇹', '+590': '🇬🇵',
  '+591': '🇧🇴', '+592': '🇬🇾', '+593': '🇪🇨', '+594': '🇬🇫', '+595': '🇵🇾', '+596': '🇲🇶',
  '+597': '🇸🇷', '+598': '🇺🇾', '+599': '🇨🇼', '+670': '🇹🇱', '+672': '🇳🇫', '+673': '🇧🇳',
  '+674': '🇳🇷', '+675': '🇵🇬', '+676': '🇹🇴', '+677': '🇸🇧', '+678': '🇻🇺', '+679': '🇫🇯',
  '+680': '🇵🇼', '+681': '🇼🇫', '+682': '🇨🇰', '+683': '🇳🇺', '+685': '🇼🇸', '+686': '🇰🇮',
  '+687': '🇳🇨', '+688': '🇹🇻', '+689': '🇵🇫', '+690': '🇹🇰', '+691': '🇫🇲', '+692': '🇲🇭',
  '+850': '🇰🇵', '+852': '🇭🇰', '+853': '🇲🇴', '+855': '🇰🇭', '+856': '🇱🇦', '+880': '🇧🇩',
  '+886': '🇹🇼', '+960': '🇲🇻', '+961': '🇱🇧', '+962': '🇯🇴', '+963': '🇸🇾', '+964': '🇮🇶',
  '+965': '🇰🇼', '+966': '🇸🇦', '+967': '🇾🇪', '+968': '🇴🇲', '+970': '🇵🇸', '+971': '🇦🇪',
  '+972': '🇮🇱', '+973': '🇧🇭', '+974': '🇶🇦', '+975': '🇧🇹', '+976': '🇲🇳', '+977': '🇳🇵',
  '+992': '🇹🇯', '+993': '🇹🇲', '+994': '🇦🇿', '+995': '🇬🇪', '+996': '🇰🇬', '+998': '🇺🇿',
};

export const KYC_OPTIONS = [
  { value: 'none', label: '无需 KYC' },
  { value: 'id_card', label: '身份证' },
  { value: 'permit', label: '港澳通行证' },
  { value: 'passport_no_visa', label: '中国护照 (无签证)' },
  { value: 'passport_visa', label: '中国护照 + 签证' },
  { value: 'mainland_agency', label: '中国内地代认证' },
  { value: 'overseas_agency', label: '境外代认证' },
];

export const PAYMENT_METHODS = [
  'WeChat', 'Alipay', 'WeChatPayHK', 'AlipayHK', 'Octopus', 'Visa', 'Mastercard', 
  'AmEx', 'JCB', 'UnionPay', 'USDT', 'TON', 'PerfectMoney', 'Crypto_Other', 
  'PayPal', 'ApplePay', 'GooglePay', 'Discover', 'DinersClub',
  'Wise', 'Revolut', 'Payoneer', 'Skrill', 'Neteller', 'WebMoney',
  'GCash', 'GrabPay', 'TouchNGo', 'LinePay', 'KakaoPay',
  'PayNow', 'FPS', 'IBAN_SEPA', 'Local_Bank', 'Other'
];

export const OPERATOR_TYPES = [
  { value: 'MNO', label: 'MNO (基础运营商)' },
  { value: 'MVNO_Branded', label: '贴牌型 MVNO' },
  { value: 'MVNO_Aggregator', label: '聚合型 MVNO' },
  { value: 'Roaming_Provider', label: '流量漫游商' },
  { value: 'TopConnect', label: 'Top Connect 及其下游' },
  { value: 'Other', label: '其他' }
];

export const NUMBER_TYPES = [
  { value: 'Mobile', label: 'Mobile (原生移动)' },
  { value: 'VoIP', label: 'VoIP (虚拟语音)' },
  { value: 'Landline', label: 'Landline (固话)' },
  { value: 'Satellite', label: 'Satellite (卫星电话)' }
];

export const ROAMING_PREREQUISITES = [
  { value: 'none', label: '无门槛 (Open)' },
  { value: 'package_required', label: '需开通套餐 (Pack Req.)' },
  { value: 'balance_threshold', label: '需余额/PAYG (PAYG/Threshold)' }
];

export const ESIM_TRANSFER_METHODS = [
    { label: '线上自助转移 (Self-Service)', value: 'Online Self-Service' },
    { label: '线下门市办理 (Offline Store)', value: 'Offline Store' },
    { label: '联网删除重扫 (Delete & Rescan)', value: 'Delete & Rescan' },
    { label: '付费补卡/重置 (Replacement/Reset)', value: 'Replacement Card' },
    { label: '联系客服人工 (Customer Service)', value: 'Customer Service' }
];

// Resolvers for ambiguous codes
export const AMBIGUOUS_REGIONS: Record<string, { code: string, name: string, flag: string }[]> = {
  '+1': [
    { code: '+1', name: 'USA (美国)', flag: '🇺🇸' },
    { code: '+1', name: 'Canada (加拿大)', flag: '🇨🇦' },
    { code: '+1', name: 'American Samoa (美属萨摩亚)', flag: '🇦🇸' },
    { code: '+1', name: 'Anguilla (安圭拉)', flag: '🇦🇮' },
    { code: '+1', name: 'Antigua & Barbuda (安提瓜和巴布达)', flag: '🇦🇬' },
    { code: '+1', name: 'Bahamas (巴哈马)', flag: '🇧🇸' },
    { code: '+1', name: 'Barbados (巴巴多斯)', flag: '🇧🇧' },
    { code: '+1', name: 'Bermuda (百慕大)', flag: '🇧🇲' },
    { code: '+1', name: 'British Virgin Is. (英属维尔京群岛)', flag: '🇻🇬' },
    { code: '+1', name: 'Cayman Is. (开曼群岛)', flag: '🇰🇾' },
    { code: '+1', name: 'Dominica (多米尼克)', flag: '🇩🇲' },
    { code: '+1', name: 'Dominican Rep. (多米尼加共和国)', flag: '🇩🇴' },
    { code: '+1', name: 'Grenada (格林纳达)', flag: '🇬🇩' },
    { code: '+1', name: 'Guam (关岛)', flag: '🇬🇺' },
    { code: '+1', name: 'Jamaica (牙买加)', flag: '🇯🇲' },
    { code: '+1', name: 'Montserrat (蒙特塞拉特)', flag: '🇲🇸' },
    { code: '+1', name: 'Northern Mariana Is. (北马里亚纳群岛)', flag: '🇲🇵' },
    { code: '+1', name: 'Puerto Rico (波多黎各)', flag: '🇵🇷' },
    { code: '+1', name: 'St. Kitts & Nevis (圣基茨和尼维斯)', flag: '🇰🇳' },
    { code: '+1', name: 'St. Lucia (圣卢西亚)', flag: '🇱🇨' },
    { code: '+1', name: 'St. Vincent & Grenadines (圣文森特和格林纳丁斯)', flag: '🇻🇨' },
    { code: '+1', name: 'Sint Maarten (荷属圣马丁)', flag: '🇸🇽' },
    { code: '+1', name: 'Trinidad & Tobago (特立尼达和多巴哥)', flag: '🇹🇹' },
    { code: '+1', name: 'Turks & Caicos Is. (特克斯和凯科斯群岛)', flag: '🇹🇨' },
    { code: '+1', name: 'US Virgin Is. (美属维尔京群岛)', flag: '🇻🇮' },
  ],
  '+7': [
    { code: '+7', name: 'Russia (俄罗斯)', flag: '🇷🇺' },
    { code: '+7', name: 'Kazakhstan (哈萨克斯坦)', flag: '🇰🇿' },
  ],
  '+39': [
    { code: '+39', name: 'Italy (意大利)', flag: '🇮🇹' },
    { code: '+3906698', name: 'Vatican (梵蒂冈)', flag: '🇻🇦' },
  ]
};

// --- New Additions for v4 ---

export const ALL_CURRENCIES = [
  // --- Most Common (Top) ---
  { code: 'CNY', label: 'CNY - Chinese Yuan', symbol: '¥' },
  { code: 'USD', label: 'USD - US Dollar', symbol: '$' },
  { code: 'HKD', label: 'HKD - Hong Kong Dollar', symbol: 'HK$' },
  { code: 'EUR', label: 'EUR - Euro', symbol: '€' },
  { code: 'GBP', label: 'GBP - British Pound', symbol: '£' },
  { code: 'JPY', label: 'JPY - Japanese Yen', symbol: '¥' },
  { code: 'SGD', label: 'SGD - Singapore Dollar', symbol: 'S$' },
  { code: 'TWD', label: 'TWD - New Taiwan Dollar', symbol: 'NT$' },
  { code: 'MYR', label: 'MYR - Malaysian Ringgit', symbol: 'RM' },
  { code: 'THB', label: 'THB - Thai Baht', symbol: '฿' },
  { code: 'AUD', label: 'AUD - Australian Dollar', symbol: 'A$' },
  { code: 'CAD', label: 'CAD - Canadian Dollar', symbol: 'C$' },
  { code: 'NZD', label: 'NZD - New Zealand Dollar', symbol: 'NZ$' },
  { code: 'KRW', label: 'KRW - South Korean Won', symbol: '₩' },
  { code: 'VND', label: 'VND - Vietnamese Dong', symbol: '₫' },
  { code: 'PHP', label: 'PHP - Philippine Peso', symbol: '₱' },
  { code: 'IDR', label: 'IDR - Indonesian Rupiah', symbol: 'Rp' },
  { code: 'RUB', label: 'RUB - Russian Ruble', symbol: '₽' },
  { code: 'KZT', label: 'KZT - Kazakhstani Tenge', symbol: '₸' },
  { code: 'TRY', label: 'TRY - Turkish Lira', symbol: '₺' },

  // --- Alphabetical List of Others ---
  { code: 'AED', label: 'AED - UAE Dirham', symbol: 'د.إ' },
  { code: 'AFN', label: 'AFN - Afghan Afghani', symbol: '؋' },
  { code: 'ALL', label: 'ALL - Albanian Lek', symbol: 'L' },
  { code: 'AMD', label: 'AMD - Armenian Dram', symbol: '֏' },
  { code: 'ANG', label: 'ANG - Netherlands Antillean Guilder', symbol: 'ƒ' },
  { code: 'AOA', label: 'AOA - Angolan Kwanza', symbol: 'Kz' },
  { code: 'ARS', label: 'ARS - Argentine Peso', symbol: '$' },
  { code: 'AWG', label: 'AWG - Aruban Florin', symbol: 'ƒ' },
  { code: 'AZN', label: 'AZN - Azerbaijani Manat', symbol: '₼' },
  { code: 'BAM', label: 'BAM - Bosnia-Herzegovina Mark', symbol: 'KM' },
  { code: 'BBD', label: 'BBD - Barbadian Dollar', symbol: '$' },
  { code: 'BDT', label: 'BDT - Bangladeshi Taka', symbol: '৳' },
  { code: 'BGN', label: 'BGN - Bulgarian Lev', symbol: 'лв' },
  { code: 'BHD', label: 'BHD - Bahraini Dinar', symbol: '.د.ب' },
  { code: 'BIF', label: 'BIF - Burundian Franc', symbol: 'Fr' },
  { code: 'BMD', label: 'BMD - Bermudian Dollar', symbol: '$' },
  { code: 'BND', label: 'BND - Brunei Dollar', symbol: '$' },
  { code: 'BOB', label: 'BOB - Bolivian Boliviano', symbol: 'Bs.' },
  { code: 'BRL', label: 'BRL - Brazilian Real', symbol: 'R$' },
  { code: 'BSD', label: 'BSD - Bahamian Dollar', symbol: '$' },
  { code: 'BTC', label: 'BTC - Bitcoin', symbol: '₿' },
  { code: 'BTN', label: 'BTN - Bhutanese Ngultrum', symbol: 'Nu.' },
  { code: 'BWP', label: 'BWP - Botswana Pula', symbol: 'P' },
  { code: 'BYN', label: 'BYN - Belarusian Ruble', symbol: 'Br' },
  { code: 'BZD', label: 'BZD - Belize Dollar', symbol: '$' },
  { code: 'CDF', label: 'CDF - Congolese Franc', symbol: 'Fr' },
  { code: 'CHF', label: 'CHF - Swiss Franc', symbol: 'Fr' },
  { code: 'CLP', label: 'CLP - Chilean Peso', symbol: '$' },
  { code: 'COP', label: 'COP - Colombian Peso', symbol: '$' },
  { code: 'CRC', label: 'CRC - Costa Rican Colón', symbol: '₡' },
  { code: 'CUP', label: 'CUP - Cuban Peso', symbol: '$' },
  { code: 'CVE', label: 'CVE - Cape Verdean Escudo', symbol: '$' },
  { code: 'CZK', label: 'CZK - Czech Koruna', symbol: 'Kč' },
  { code: 'DJF', label: 'DJF - Djiboutian Franc', symbol: 'Fr' },
  { code: 'DKK', label: 'DKK - Danish Krone', symbol: 'kr' },
  { code: 'DOP', label: 'DOP - Dominican Peso', symbol: 'RD$' },
  { code: 'DZD', label: 'DZD - Algerian Dinar', symbol: 'د.ج' },
  { code: 'EGP', label: 'EGP - Egyptian Pound', symbol: '£' },
  { code: 'ERN', label: 'ERN - Eritrean Nakfa', symbol: 'Nfk' },
  { code: 'ETB', label: 'ETB - Ethiopian Birr', symbol: 'Br' },
  { code: 'FJD', label: 'FJD - Fijian Dollar', symbol: '$' },
  { code: 'FKP', label: 'FKP - Falkland Islands Pound', symbol: '£' },
  { code: 'GEL', label: 'GEL - Georgian Lari', symbol: '₾' },
  { code: 'GGP', label: 'GGP - Guernsey Pound', symbol: '£' },
  { code: 'GHS', label: 'GHS - Ghanaian Cedi', symbol: '₵' },
  { code: 'GIP', label: 'GIP - Gibraltar Pound', symbol: '£' },
  { code: 'GMD', label: 'GMD - Gambian Dalasi', symbol: 'D' },
  { code: 'GNF', label: 'GNF - Guinean Franc', symbol: 'Fr' },
  { code: 'GTQ', label: 'GTQ - Guatemalan Quetzal', symbol: 'Q' },
  { code: 'GYD', label: 'GYD - Guyanese Dollar', symbol: '$' },
  { code: 'HNL', label: 'HNL - Honduran Lempira', symbol: 'L' },
  { code: 'HRK', label: 'HRK - Croatian Kuna', symbol: 'kn' },
  { code: 'HTG', label: 'HTG - Haitian Gourde', symbol: 'G' },
  { code: 'HUF', label: 'HUF - Hungarian Forint', symbol: 'Ft' },
  { code: 'ILS', label: 'ILS - Israeli New Shekel', symbol: '₪' },
  { code: 'IMP', label: 'IMP - Manx Pound', symbol: '£' },
  { code: 'INR', label: 'INR - Indian Rupee', symbol: '₹' },
  { code: 'IQD', label: 'IQD - Iraqi Dinar', symbol: 'ع.د' },
  { code: 'IRR', label: 'IRR - Iranian Rial', symbol: '﷼' },
  { code: 'ISK', label: 'ISK - Icelandic Króna', symbol: 'kr' },
  { code: 'JEP', label: 'JEP - Jersey Pound', symbol: '£' },
  { code: 'JMD', label: 'JMD - Jamaican Dollar', symbol: '$' },
  { code: 'JOD', label: 'JOD - Jordanian Dinar', symbol: 'د.ا' },
  { code: 'KES', label: 'KES - Kenyan Shilling', symbol: 'Sh' },
  { code: 'KGS', label: 'KGS - Kyrgyzstani Som', symbol: 'с' },
  { code: 'KHR', label: 'KHR - Cambodian Riel', symbol: '៛' },
  { code: 'KMF', label: 'KMF - Comorian Franc', symbol: 'Fr' },
  { code: 'KPW', label: 'KPW - North Korean Won', symbol: '₩' },
  { code: 'KWD', label: 'KWD - Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'KYD', label: 'KYD - Cayman Islands Dollar', symbol: '$' },
  { code: 'LAK', label: 'LAK - Lao Kip', symbol: '₭' },
  { code: 'LBP', label: 'LBP - Lebanese Pound', symbol: 'ل.ل' },
  { code: 'LKR', label: 'LKR - Sri Lankan Rupee', symbol: 'Rs' },
  { code: 'LRD', label: 'LRD - Liberian Dollar', symbol: '$' },
  { code: 'LSL', label: 'LSL - Lesotho Loti', symbol: 'L' },
  { code: 'LYD', label: 'LYD - Libyan Dinar', symbol: 'ل.د' },
  { code: 'MAD', label: 'MAD - Moroccan Dirham', symbol: 'dh' },
  { code: 'MDL', label: 'MDL - Moldovan Leu', symbol: 'L' },
  { code: 'MGA', label: 'MGA - Malagasy Ariary', symbol: 'Ar' },
  { code: 'MKD', label: 'MKD - Macedonian Denar', symbol: 'ден' },
  { code: 'MMK', label: 'MMK - Burmese Kyat', symbol: 'K' },
  { code: 'MNT', label: 'MNT - Mongolian Tögrög', symbol: '₮' },
  { code: 'MOP', label: 'MOP - Macanese Pataca', symbol: 'P' },
  { code: 'MRU', label: 'MRU - Mauritanian Ouguiya', symbol: 'UM' },
  { code: 'MUR', label: 'MUR - Mauritian Rupee', symbol: '₨' },
  { code: 'MVR', label: 'MVR - Maldivian Rufiyaa', symbol: 'Rf' },
  { code: 'MWK', label: 'MWK - Malawian Kwacha', symbol: 'MK' },
  { code: 'MXN', label: 'MXN - Mexican Peso', symbol: '$' },
  { code: 'MZN', label: 'MZN - Mozambican Metical', symbol: 'MT' },
  { code: 'NAD', label: 'NAD - Namibian Dollar', symbol: '$' },
  { code: 'NGN', label: 'NGN - Nigerian Naira', symbol: '₦' },
  { code: 'NIO', label: 'NIO - Nicaraguan Córdoba', symbol: 'C$' },
  { code: 'NOK', label: 'NOK - Norwegian Krone', symbol: 'kr' },
  { code: 'NPR', label: 'NPR - Nepalese Rupee', symbol: '₨' },
  { code: 'OMR', label: 'OMR - Omani Rial', symbol: 'ر.ع.' },
  { code: 'PAB', label: 'PAB - Panamanian Balboa', symbol: 'B/.' },
  { code: 'PEN', label: 'PEN - Peruvian Sol', symbol: 'S/.' },
  { code: 'PGK', label: 'PGK - Papua New Guinean Kina', symbol: 'K' },
  { code: 'PKR', label: 'PKR - Pakistani Rupee', symbol: '₨' },
  { code: 'PLN', label: 'PLN - Polish Złoty', symbol: 'zł' },
  { code: 'PYG', label: 'PYG - Paraguayan Guaraní', symbol: '₲' },
  { code: 'QAR', label: 'QAR - Qatari Riyal', symbol: 'ر.ق' },
  { code: 'RON', label: 'RON - Romanian Leu', symbol: 'lei' },
  { code: 'RSD', label: 'RSD - Serbian Dinar', symbol: 'дин' },
  { code: 'RWF', label: 'RWF - Rwandan Franc', symbol: 'Fr' },
  { code: 'SAR', label: 'SAR - Saudi Riyal', symbol: 'ر.س' },
  { code: 'SBD', label: 'SBD - Solomon Islands Dollar', symbol: '$' },
  { code: 'SCR', label: 'SCR - Seychellois Rupee', symbol: '₨' },
  { code: 'SDG', label: 'SDG - Sudanese Pound', symbol: '£' },
  { code: 'SEK', label: 'SEK - Swedish Krona', symbol: 'kr' },
  { code: 'SHP', label: 'SHP - Saint Helena Pound', symbol: '£' },
  { code: 'SLL', label: 'SLL - Sierra Leonean Leone', symbol: 'Le' },
  { code: 'SOS', label: 'SOS - Somali Shilling', symbol: 'Sh' },
  { code: 'SRD', label: 'SRD - Surinamese Dollar', symbol: '$' },
  { code: 'SSP', label: 'SSP - South Sudanese Pound', symbol: '£' },
  { code: 'STN', label: 'STN - São Tomé and Príncipe Dobra', symbol: 'Db' },
  { code: 'SYP', label: 'SYP - Syrian Pound', symbol: '£' },
  { code: 'SZL', label: 'SZL - Eswatini Lilangeni', symbol: 'L' },
  { code: 'TJS', label: 'TJS - Tajikistani Somoni', symbol: 'ЅM' },
  { code: 'TMT', label: 'TMT - Turkmenistani Manat', symbol: 'm' },
  { code: 'TND', label: 'TND - Tunisian Dinar', symbol: 'د.ت' },
  { code: 'TOP', label: 'TOP - Tongan Paʻanga', symbol: 'T$' },
  { code: 'TTD', label: 'TTD - Trinidad and Tobago Dollar', symbol: '$' },
  { code: 'TZS', label: 'TZS - Tanzanian Shilling', symbol: 'Sh' },
  { code: 'UAH', label: 'UAH - Ukrainian Hryvnia', symbol: '₴' },
  { code: 'UGX', label: 'UGX - Ugandan Shilling', symbol: 'Sh' },
  { code: 'UYU', label: 'UYU - Uruguayan Peso', symbol: '$' },
  { code: 'UZS', label: 'UZS - Uzbekistani Soʻm', symbol: 'so\'m' },
  { code: 'VES', label: 'VES - Venezuelan Bolívar', symbol: 'Bs.' },
  { code: 'VUV', label: 'VUV - Vanuatu Vatu', symbol: 'Vt' },
  { code: 'WST', label: 'WST - Samoan Tālā', symbol: 'T' },
  { code: 'XAF', label: 'XAF - Central African CFA Franc', symbol: 'Fr' },
  { code: 'XCD', label: 'XCD - East Caribbean Dollar', symbol: '$' },
  { code: 'XOF', label: 'XOF - West African CFA Franc', symbol: 'Fr' },
  { code: 'XPF', label: 'XPF - CFP Franc', symbol: 'Fr' },
  { code: 'YER', label: 'YER - Yemeni Rial', symbol: '﷼' },
  { code: 'ZAR', label: 'ZAR - South African Rand', symbol: 'R' },
  { code: 'ZMW', label: 'ZMW - Zambian Kwacha', symbol: 'ZK' },
  { code: 'ZWL', label: 'ZWL - Zimbabwean Dollar', symbol: '$' },
];

export const ESIM_DEVICE_PRESETS = [
    { name: "5ber Standard", eidPrefix: "", method: "App Writing (Android only)" },
    { name: "5ber Premium", eidPrefix: "", method: "App Writing (Android only)" },
    { name: "Estk.me Eco", eidPrefix: "", method: "Cloud Enhanced / Local" },
    { name: "Estk.me Pro", eidPrefix: "", method: "Cloud Enhanced / Local" },
    { name: "RedteaGo", eidPrefix: "89860", method: "App Writing" },
    { name: "Pixel 7/8", eidPrefix: "890", method: "Native OS Menu" },
    { name: "iPhone 14/15", eidPrefix: "890", method: "Native OS Menu" }
];
